Add check-for-merge-conflicts.sh script and static code analysis workflow

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -13,12 +13,45 @@ concurrency:
 jobs:
   #####################################################################################################################
   #                                                                                                                   #
+  #   Static Code Analysis                                                                                            #
+  #                                                                                                                   #
+  #####################################################################################################################
+  static_code_analysis:
+    name: Static Code Analysis
+    runs-on: [ubuntu-22.04]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Check for unresolved merge conflicts
+        run: |
+          ./.github/workflows/check-for-merge-conflicts.sh
+        # continue-on-error: true
+
+      - name: Check for syntax and types
+        run: |
+          ./.github/workflows/check-for-syntax-and-types.sh
+        # continue-on-error: true
+
+      # this is needed to ensure that the pipeline fails if any of the previous steps failed
+      # - name: Check for any previous step failure
+      #   if: ${{ always() }}
+      #   run: |
+      #     if [ "${{ job.status }}" != "success" ]; then
+      #       echo "Failing the job because one or more steps failed"
+      #       exit 1
+      #     fi
+
+
+  #####################################################################################################################
+  #                                                                                                                   #
   #   Build on Linux                                                                                                  #
   #                                                                                                                   #
   #####################################################################################################################
   build_on_linux:
-    runs-on: [ubuntu-22.04]
     name: Build on Linux
+    runs-on: [ubuntu-22.04]
+    needs: [static_code_analysis]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -47,8 +80,9 @@ jobs:
   #                                                                                                                   #
   #####################################################################################################################
   build_on_mac:
-    runs-on: [macos-13]
     name: Build on Mac
+    runs-on: [macos-13]
+    needs: [static_code_analysis]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
